import type { ApplicationDef, ApplicationId } from "./types";

export const APPLICATIONS: ApplicationDef[] = [
  {
    id: "conveyor",
    name: "Belt conveyor",
    short: "Belt",
    group: "linear",
    description:
      "Horizontal or inclined belt conveying bulk or unit loads. Sizes the drive pulley from belt pull, speed and acceleration.",
    fields: [
      {
        key: "payloadKg",
        label: "Payload on belt",
        unit: "kg",
        metricToSi: 1,
        defaultValue: 800,
        min: 1,
        max: 50000,
        step: 10,
        hint: "Total moving mass on the carrying side, including product.",
      },
      {
        key: "beltMassKg",
        label: "Belt + idler equivalent mass",
        unit: "kg",
        metricToSi: 1,
        defaultValue: 220,
        min: 0,
        max: 20000,
        step: 5,
        hint: "Rotating parts reflected as equivalent translating mass.",
      },
      {
        key: "speedMps",
        label: "Belt speed",
        unit: "m/s",
        metricToSi: 1,
        defaultValue: 0.6,
        min: 0.01,
        max: 8,
        step: 0.05,
        hint: "Steady-state conveying speed.",
      },
      {
        key: "pulleyDiaM",
        label: "Drive pulley diameter",
        unit: "mm",
        metricToSi: 0.001,
        defaultValue: 220,
        min: 40,
        max: 2000,
        step: 5,
        hint: "Pitch diameter of the drive drum or pulley.",
      },
      {
        key: "inclineDeg",
        label: "Incline",
        unit: "deg",
        metricToSi: 1,
        defaultValue: 8,
        min: 0,
        max: 30,
        step: 0.5,
        hint: "Positive uphill in the conveying direction.",
      },
      {
        key: "mu",
        label: "Equivalent friction μ",
        unit: "—",
        metricToSi: 1,
        defaultValue: 0.12,
        min: 0.02,
        max: 0.6,
        step: 0.01,
        hint: "Lumped idler, belt and skirt friction. 0.08–0.15 typical for roller beds.",
      },
      {
        key: "accelTimeS",
        label: "Acceleration time",
        unit: "s",
        metricToSi: 1,
        defaultValue: 1.5,
        min: 0.1,
        max: 30,
        step: 0.1,
        hint: "Time to reach belt speed from standstill.",
      },
      {
        key: "efficiency",
        label: "Drive efficiency",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 92,
        min: 40,
        max: 99,
        step: 1,
        hint: "Pulley wrap, couplings and any existing reduction.",
      },
      {
        key: "dutyCycle",
        label: "Duty cycle",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 80,
        min: 5,
        max: 100,
        step: 5,
        hint: "Running time as a fraction of the cycle.",
      },
      {
        key: "safetyFactor",
        label: "Safety factor",
        unit: "—",
        metricToSi: 1,
        defaultValue: 1.4,
        min: 1,
        max: 3,
        step: 0.05,
        hint: "Covers start-up, wear and unmodelled drag.",
      },
    ],
    selects: [
      {
        key: "dutyType",
        label: "IEC duty",
        defaultValue: "S1",
        hint: "S1 continuous, S3 intermittent, S5 intermittent with electric braking.",
        options: [
          { value: "S1", label: "S1 — continuous" },
          { value: "S3", label: "S3 — intermittent" },
          { value: "S5", label: "S5 — intermittent + braking" },
        ],
      },
    ],
  },
  {
    id: "roller-conveyor",
    name: "Driven roller conveyor",
    short: "Rollers",
    group: "linear",
    description:
      "Line-shaft or motorized-roller beds. Pull is dominated by rolling resistance and acceleration of product plus rollers.",
    fields: [
      {
        key: "payloadKg",
        label: "Product mass",
        unit: "kg",
        metricToSi: 1,
        defaultValue: 450,
        min: 1,
        max: 20000,
        step: 5,
        hint: "Maximum simultaneous product on the driven zone.",
      },
      {
        key: "rollerMassKg",
        label: "Driven roller mass",
        unit: "kg",
        metricToSi: 1,
        defaultValue: 80,
        min: 0,
        max: 5000,
        step: 1,
        hint: "Sum of rotating roller masses in the zone.",
      },
      {
        key: "speedMps",
        label: "Transport speed",
        unit: "m/s",
        metricToSi: 1,
        defaultValue: 0.45,
        min: 0.01,
        max: 4,
        step: 0.05,
        hint: "Linear speed of the package.",
      },
      {
        key: "rollerDiaM",
        label: "Roller diameter",
        unit: "mm",
        metricToSi: 0.001,
        defaultValue: 50,
        min: 20,
        max: 200,
        step: 1,
        hint: "Outer diameter of the driven rollers.",
      },
      {
        key: "mu",
        label: "Rolling resistance c",
        unit: "—",
        metricToSi: 1,
        defaultValue: 0.03,
        min: 0.005,
        max: 0.2,
        step: 0.005,
        hint: "0.02–0.04 for clean steel rollers on cartons.",
      },
      {
        key: "accelTimeS",
        label: "Acceleration time",
        unit: "s",
        metricToSi: 1,
        defaultValue: 0.6,
        min: 0.1,
        max: 10,
        step: 0.1,
        hint: "Zone start time.",
      },
      {
        key: "efficiency",
        label: "Drive efficiency",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 88,
        min: 40,
        max: 99,
        step: 1,
        hint: "Poly-V, line-shaft or MDR gearbox efficiency.",
      },
      {
        key: "dutyCycle",
        label: "Duty cycle",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 55,
        min: 5,
        max: 100,
        step: 5,
        hint: "Accumulation lines often sit well below 100%.",
      },
      {
        key: "safetyFactor",
        label: "Safety factor",
        unit: "—",
        metricToSi: 1,
        defaultValue: 1.5,
        min: 1,
        max: 3,
        step: 0.05,
        hint: "Covers dirty rollers and misaligned packages.",
      },
    ],
    selects: [
      {
        key: "dutyType",
        label: "IEC duty",
        defaultValue: "S3",
        hint: "Indexed zones are usually S3.",
        options: [
          { value: "S1", label: "S1 — continuous" },
          { value: "S3", label: "S3 — intermittent" },
          { value: "S5", label: "S5 — intermittent + braking" },
        ],
      },
    ],
  },
  {
    id: "crane",
    name: "Crane / hoist",
    short: "Hoist",
    group: "lifting",
    description:
      "Wire-rope or chain hoist. Torque at the drum accounts for reeving, hook speed and gravity plus acceleration.",
    fields: [
      {
        key: "payloadKg",
        label: "Hook load",
        unit: "kg",
        metricToSi: 1,
        defaultValue: 2000,
        min: 10,
        max: 100000,
        step: 10,
        hint: "Rated load at the hook.",
      },
      {
        key: "hookSpeedMps",
        label: "Hook speed",
        unit: "m/min",
        metricToSi: 1 / 60,
        defaultValue: 8,
        min: 0.2,
        max: 60,
        step: 0.5,
        hint: "Steady hoist speed of the load.",
      },
      {
        key: "drumDiaM",
        label: "Drum / sheave diameter",
        unit: "mm",
        metricToSi: 0.001,
        defaultValue: 320,
        min: 50,
        max: 2000,
        step: 5,
        hint: "Pitch diameter where the rope winds.",
      },
      {
        key: "falls",
        label: "Number of falls",
        unit: "—",
        metricToSi: 1,
        defaultValue: 4,
        min: 1,
        max: 16,
        step: 1,
        hint: "Reeving parts supporting the load.",
      },
      {
        key: "accelTimeS",
        label: "Acceleration time",
        unit: "s",
        metricToSi: 1,
        defaultValue: 1.2,
        min: 0.2,
        max: 10,
        step: 0.1,
        hint: "Time to rated hook speed.",
      },
      {
        key: "efficiency",
        label: "Reeving + gearbox η",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 88,
        min: 40,
        max: 98,
        step: 1,
        hint: "Sheaves, drum and any existing reduction.",
      },
      {
        key: "dutyCycle",
        label: "Duty cycle",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 40,
        min: 5,
        max: 100,
        step: 5,
        hint: "FEM / ISO hoist duty as running fraction.",
      },
      {
        key: "safetyFactor",
        label: "Safety factor",
        unit: "—",
        metricToSi: 1,
        defaultValue: 1.6,
        min: 1.1,
        max: 3,
        step: 0.05,
        hint: "Lifting applications use a higher factor than conveyors.",
      },
    ],
    selects: [
      {
        key: "dutyType",
        label: "IEC duty",
        defaultValue: "S3",
        hint: "Most hoists are intermittent S3 or S5.",
        options: [
          { value: "S1", label: "S1 — continuous" },
          { value: "S3", label: "S3 — intermittent" },
          { value: "S5", label: "S5 — intermittent + braking" },
        ],
      },
    ],
  },
  {
    id: "winch",
    name: "Winch / capstan",
    short: "Winch",
    group: "lifting",
    description:
      "Single-layer drum or capstan pulling a cable. Same physics as a one-fall hoist, including holding torque.",
    fields: [
      {
        key: "payloadKg",
        label: "Line pull mass equivalent",
        unit: "kg",
        metricToSi: 1,
        defaultValue: 600,
        min: 5,
        max: 50000,
        step: 5,
        hint: "F / g if you know line pull in newtons.",
      },
      {
        key: "lineSpeedMps",
        label: "Line speed",
        unit: "m/min",
        metricToSi: 1 / 60,
        defaultValue: 12,
        min: 0.2,
        max: 80,
        step: 0.5,
        hint: "Cable speed at the drum.",
      },
      {
        key: "drumDiaM",
        label: "Drum diameter",
        unit: "mm",
        metricToSi: 0.001,
        defaultValue: 280,
        min: 40,
        max: 2000,
        step: 5,
        hint: "Mean winding diameter.",
      },
      {
        key: "accelTimeS",
        label: "Acceleration time",
        unit: "s",
        metricToSi: 1,
        defaultValue: 1,
        min: 0.2,
        max: 15,
        step: 0.1,
        hint: "Time to line speed.",
      },
      {
        key: "efficiency",
        label: "Drive efficiency",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 90,
        min: 40,
        max: 98,
        step: 1,
        hint: "Drum bearings plus existing reduction.",
      },
      {
        key: "dutyCycle",
        label: "Duty cycle",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 35,
        min: 5,
        max: 100,
        step: 5,
        hint: "Winches are rarely continuous.",
      },
      {
        key: "safetyFactor",
        label: "Safety factor",
        unit: "—",
        metricToSi: 1,
        defaultValue: 1.7,
        min: 1.1,
        max: 3,
        step: 0.05,
        hint: "Includes snatch loads.",
      },
    ],
    selects: [
      {
        key: "dutyType",
        label: "IEC duty",
        defaultValue: "S3",
        hint: "Typical winch duty.",
        options: [
          { value: "S1", label: "S1 — continuous" },
          { value: "S3", label: "S3 — intermittent" },
          { value: "S5", label: "S5 — intermittent + braking" },
        ],
      },
    ],
  },
  {
    id: "ball-screw",
    name: "Ball screw / linear actuator",
    short: "Screw",
    group: "linear",
    description:
      "Converts rotary torque to axial force through screw lead. Handles horizontal, inclined and vertical axes.",
    fields: [
      {
        key: "payloadKg",
        label: "Moved mass",
        unit: "kg",
        metricToSi: 1,
        defaultValue: 180,
        min: 0.5,
        max: 10000,
        step: 1,
        hint: "Carriage, tooling and workpiece.",
      },
      {
        key: "speedMps",
        label: "Linear speed",
        unit: "mm/s",
        metricToSi: 0.001,
        defaultValue: 250,
        min: 1,
        max: 2000,
        step: 5,
        hint: "Rapid or process speed, whichever is higher for sizing.",
      },
      {
        key: "leadM",
        label: "Screw lead",
        unit: "mm/rev",
        metricToSi: 0.001,
        defaultValue: 10,
        min: 1,
        max: 50,
        step: 1,
        hint: "Axial travel per revolution.",
      },
      {
        key: "inclineDeg",
        label: "Axis incline",
        unit: "deg",
        metricToSi: 1,
        defaultValue: 0,
        min: 0,
        max: 90,
        step: 1,
        hint: "0 horizontal, 90 vertical lift.",
        visibleWhen: { key: "orientation", values: ["inclined"] },
      },
      {
        key: "mu",
        label: "Guide friction μ",
        unit: "—",
        metricToSi: 1,
        defaultValue: 0.01,
        min: 0,
        max: 0.3,
        step: 0.005,
        hint: "Profile rail ~0.005–0.02; dove-tail much higher.",
      },
      {
        key: "preloadN",
        label: "Seal / preload force",
        unit: "N",
        metricToSi: 1,
        defaultValue: 40,
        min: 0,
        max: 5000,
        step: 5,
        hint: "Wiper drag plus any intentional preload.",
      },
      {
        key: "accelTimeS",
        label: "Acceleration time",
        unit: "s",
        metricToSi: 1,
        defaultValue: 0.25,
        min: 0.05,
        max: 5,
        step: 0.05,
        hint: "Time to linear speed.",
      },
      {
        key: "efficiency",
        label: "Screw efficiency",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 90,
        min: 30,
        max: 98,
        step: 1,
        hint: "Ball screw ~90%, acme / trapezoidal ~30–50%.",
      },
      {
        key: "dutyCycle",
        label: "Duty cycle",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 50,
        min: 5,
        max: 100,
        step: 5,
        hint: "Move time over cycle time.",
      },
      {
        key: "safetyFactor",
        label: "Safety factor",
        unit: "—",
        metricToSi: 1,
        defaultValue: 1.35,
        min: 1,
        max: 3,
        step: 0.05,
        hint: "Servo axes often 1.3–1.5.",
      },
    ],
    selects: [
      {
        key: "orientation",
        label: "Axis orientation",
        defaultValue: "horizontal",
        hint: "Vertical includes gravity on raise and lower, plus holding torque.",
        options: [
          { value: "horizontal", label: "Horizontal" },
          { value: "inclined", label: "Inclined" },
          { value: "vertical", label: "Vertical lift" },
        ],
      },
      {
        key: "dutyType",
        label: "IEC duty",
        defaultValue: "S5",
        hint: "Positioning axes with braking are S5.",
        options: [
          { value: "S1", label: "S1 — continuous" },
          { value: "S3", label: "S3 — intermittent" },
          { value: "S5", label: "S5 — intermittent + braking" },
        ],
      },
    ],
  },
  {
    id: "rack-pinion",
    name: "Rack and pinion",
    short: "Rack",
    group: "linear",
    description:
      "Gantry and long-travel axes. Torque is force times pinion pitch radius, with reflected linear inertia.",
    fields: [
      {
        key: "payloadKg",
        label: "Moved mass",
        unit: "kg",
        metricToSi: 1,
        defaultValue: 350,
        min: 1,
        max: 20000,
        step: 5,
        hint: "Carriage plus payload.",
      },
      {
        key: "speedMps",
        label: "Linear speed",
        unit: "m/s",
        metricToSi: 1,
        defaultValue: 1.2,
        min: 0.05,
        max: 6,
        step: 0.05,
        hint: "Rapid traverse.",
      },
      {
        key: "pinionDiaM",
        label: "Pinion pitch diameter",
        unit: "mm",
        metricToSi: 0.001,
        defaultValue: 80,
        min: 20,
        max: 400,
        step: 1,
        hint: "Pitch circle of the pinion.",
      },
      {
        key: "mu",
        label: "Guide friction μ",
        unit: "—",
        metricToSi: 1,
        defaultValue: 0.015,
        min: 0,
        max: 0.3,
        step: 0.005,
        hint: "Linear guide friction.",
      },
      {
        key: "inclineDeg",
        label: "Axis incline",
        unit: "deg",
        metricToSi: 1,
        defaultValue: 0,
        min: 0,
        max: 90,
        step: 1,
        hint: "0 horizontal. Used when orientation is inclined.",
        visibleWhen: { key: "orientation", values: ["inclined"] },
      },
      {
        key: "accelTimeS",
        label: "Acceleration time",
        unit: "s",
        metricToSi: 1,
        defaultValue: 0.4,
        min: 0.05,
        max: 8,
        step: 0.05,
        hint: "Time to traverse speed.",
      },
      {
        key: "efficiency",
        label: "Mesh efficiency",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 95,
        min: 70,
        max: 99,
        step: 1,
        hint: "Straight or helical rack mesh.",
      },
      {
        key: "dutyCycle",
        label: "Duty cycle",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 45,
        min: 5,
        max: 100,
        step: 5,
        hint: "Move time over cycle time.",
      },
      {
        key: "safetyFactor",
        label: "Safety factor",
        unit: "—",
        metricToSi: 1,
        defaultValue: 1.4,
        min: 1,
        max: 3,
        step: 0.05,
        hint: "Covers rack contamination and mesh wear.",
      },
    ],
    selects: [
      {
        key: "orientation",
        label: "Axis orientation",
        defaultValue: "horizontal",
        hint: "Use vertical for a lift or Z rack.",
        options: [
          { value: "horizontal", label: "Horizontal" },
          { value: "inclined", label: "Inclined" },
          { value: "vertical", label: "Vertical lift" },
        ],
      },
      {
        key: "dutyType",
        label: "IEC duty",
        defaultValue: "S5",
        hint: "Gantry axes are usually S5.",
        options: [
          { value: "S1", label: "S1 — continuous" },
          { value: "S3", label: "S3 — intermittent" },
          { value: "S5", label: "S5 — intermittent + braking" },
        ],
      },
    ],
  },
  {
    id: "gantry",
    name: "Gantry / cartesian axis",
    short: "Gantry",
    group: "linear",
    description:
      "Belt-driven linear module. Force at the belt from mass, friction and accel; torque from pulley radius.",
    fields: [
      {
        key: "payloadKg",
        label: "Moved mass",
        unit: "kg",
        metricToSi: 1,
        defaultValue: 55,
        min: 0.2,
        max: 2000,
        step: 1,
        hint: "Carriage, end-effector and part.",
      },
      {
        key: "speedMps",
        label: "Linear speed",
        unit: "m/s",
        metricToSi: 1,
        defaultValue: 2,
        min: 0.05,
        max: 10,
        step: 0.05,
        hint: "Peak traverse speed.",
      },
      {
        key: "pulleyDiaM",
        label: "Drive pulley diameter",
        unit: "mm",
        metricToSi: 0.001,
        defaultValue: 48,
        min: 16,
        max: 200,
        step: 1,
        hint: "Pitch diameter of the timing pulley.",
      },
      {
        key: "mu",
        label: "Guide friction μ",
        unit: "—",
        metricToSi: 1,
        defaultValue: 0.012,
        min: 0,
        max: 0.2,
        step: 0.002,
        hint: "Rail + belt tooth friction lumped.",
      },
      {
        key: "accelTimeS",
        label: "Acceleration time",
        unit: "s",
        metricToSi: 1,
        defaultValue: 0.2,
        min: 0.05,
        max: 4,
        step: 0.05,
        hint: "Aggressive pick-and-place ramps are 0.1–0.3 s.",
      },
      {
        key: "efficiency",
        label: "Belt efficiency",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 95,
        min: 70,
        max: 99,
        step: 1,
        hint: "Timing belt typically 94–97%.",
      },
      {
        key: "dutyCycle",
        label: "Duty cycle",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 60,
        min: 5,
        max: 100,
        step: 5,
        hint: "High-cycle machines approach 70%.",
      },
      {
        key: "safetyFactor",
        label: "Safety factor",
        unit: "—",
        metricToSi: 1,
        defaultValue: 1.3,
        min: 1,
        max: 3,
        step: 0.05,
        hint: "Servo sizing commonly 1.25–1.4.",
      },
    ],
    selects: [
      {
        key: "orientation",
        label: "Axis orientation",
        defaultValue: "horizontal",
        hint: "Vertical is a belt-driven Z lift. Gravity acts on raise and lower.",
        options: [
          { value: "horizontal", label: "Horizontal" },
          { value: "vertical", label: "Vertical lift" },
        ],
      },
      {
        key: "dutyType",
        label: "IEC duty",
        defaultValue: "S5",
        hint: "Cyclic gantries are S5.",
        options: [
          { value: "S1", label: "S1 — continuous" },
          { value: "S3", label: "S3 — intermittent" },
          { value: "S5", label: "S5 — intermittent + braking" },
        ],
      },
    ],
  },
  {
    id: "vertical-lift",
    name: "Vertical linear lift",
    short: "Lift",
    group: "lifting",
    description:
      "Z-axis lift on a ball screw, toothed belt or rack. Sizes raise, lower and holding torque including gravity.",
    fields: [
      {
        key: "payloadKg",
        label: "Lifted mass",
        unit: "kg",
        metricToSi: 1,
        defaultValue: 250,
        min: 1,
        max: 20000,
        step: 1,
        hint: "Carriage, fixture and payload.",
      },
      {
        key: "speedMps",
        label: "Lift speed",
        unit: "mm/s",
        metricToSi: 0.001,
        defaultValue: 200,
        min: 1,
        max: 2000,
        step: 5,
        hint: "Steady raise / lower speed.",
      },
      {
        key: "leadM",
        label: "Screw lead",
        unit: "mm/rev",
        metricToSi: 0.001,
        defaultValue: 10,
        min: 1,
        max: 50,
        step: 1,
        hint: "Ball-screw lead. Hidden for belt and rack.",
        visibleWhen: { key: "mechanism", values: ["ball-screw"] },
      },
      {
        key: "pulleyDiaM",
        label: "Drive pulley diameter",
        unit: "mm",
        metricToSi: 0.001,
        defaultValue: 48,
        min: 16,
        max: 400,
        step: 1,
        hint: "Timing-pulley pitch diameter.",
        visibleWhen: { key: "mechanism", values: ["belt"] },
      },
      {
        key: "pinionDiaM",
        label: "Pinion pitch diameter",
        unit: "mm",
        metricToSi: 0.001,
        defaultValue: 80,
        min: 20,
        max: 400,
        step: 1,
        hint: "Rack pinion pitch circle.",
        visibleWhen: { key: "mechanism", values: ["rack"] },
      },
      {
        key: "mu",
        label: "Guide friction μ",
        unit: "—",
        metricToSi: 1,
        defaultValue: 0.01,
        min: 0,
        max: 0.2,
        step: 0.005,
        hint: "Profile-rail friction. Vertical gravity is separate.",
      },
      {
        key: "preloadN",
        label: "Seal / wiper drag",
        unit: "N",
        metricToSi: 1,
        defaultValue: 40,
        min: 0,
        max: 5000,
        step: 5,
        hint: "Constant drag, independent of gravity.",
      },
      {
        key: "accelTimeS",
        label: "Acceleration time",
        unit: "s",
        metricToSi: 1,
        defaultValue: 0.3,
        min: 0.05,
        max: 8,
        step: 0.05,
        hint: "Time to lift speed.",
      },
      {
        key: "efficiency",
        label: "Mechanism efficiency",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 90,
        min: 30,
        max: 98,
        step: 1,
        hint: "Ball screw ~90%, belt ~95%, rack ~95%, acme much lower.",
      },
      {
        key: "dutyCycle",
        label: "Duty cycle",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 40,
        min: 5,
        max: 100,
        step: 5,
        hint: "Move time over cycle time.",
      },
      {
        key: "safetyFactor",
        label: "Safety factor",
        unit: "—",
        metricToSi: 1,
        defaultValue: 1.5,
        min: 1.1,
        max: 3,
        step: 0.05,
        hint: "Lifts use a higher factor than horizontal axes.",
      },
    ],
    selects: [
      {
        key: "mechanism",
        label: "Lift mechanism",
        defaultValue: "ball-screw",
        hint: "Changes the torque conversion from axial force.",
        options: [
          { value: "ball-screw", label: "Ball screw" },
          { value: "belt", label: "Toothed belt" },
          { value: "rack", label: "Rack and pinion" },
        ],
      },
      {
        key: "dutyType",
        label: "IEC duty",
        defaultValue: "S5",
        hint: "Lifts with electric braking are S5.",
        options: [
          { value: "S1", label: "S1 — continuous" },
          { value: "S3", label: "S3 — intermittent" },
          { value: "S5", label: "S5 — intermittent + braking" },
        ],
      },
    ],
  },
  {
    id: "rotary-table",
    name: "Rotary table / indexer",
    short: "Rotary",
    group: "rotary",
    description:
      "Indexing tables and turntables. Torque from reflected inertia and angular acceleration, plus friction and unbalance.",
    fields: [
      {
        key: "tableInertia",
        label: "Table + fixture inertia",
        unit: "kg·m²",
        metricToSi: 1,
        defaultValue: 12,
        min: 0.01,
        max: 5000,
        step: 0.1,
        hint: "J about the rotation axis. Use ½ m r² for a disk.",
      },
      {
        key: "payloadInertia",
        label: "Payload inertia",
        unit: "kg·m²",
        metricToSi: 1,
        defaultValue: 4,
        min: 0,
        max: 5000,
        step: 0.1,
        hint: "Parts sitting on the table, about the same axis.",
      },
      {
        key: "speedRpm",
        label: "Table speed",
        unit: "rpm",
        metricToSi: 1,
        defaultValue: 30,
        min: 0.2,
        max: 600,
        step: 1,
        hint: "Indexing or continuous rotation speed.",
      },
      {
        key: "fricTorqueNm",
        label: "Friction / bearing torque",
        unit: "N·m",
        metricToSi: 1,
        defaultValue: 8,
        min: 0,
        max: 2000,
        step: 0.5,
        hint: "Seal and bearing drag at the table.",
      },
      {
        key: "unbalanceNm",
        label: "Unbalance / gravity torque",
        unit: "N·m",
        metricToSi: 1,
        defaultValue: 0,
        min: 0,
        max: 5000,
        step: 1,
        hint: "m·g·e for an offset payload on a tilting axis.",
      },
      {
        key: "accelTimeS",
        label: "Acceleration time",
        unit: "s",
        metricToSi: 1,
        defaultValue: 0.8,
        min: 0.05,
        max: 20,
        step: 0.05,
        hint: "Time to table speed.",
      },
      {
        key: "efficiency",
        label: "Existing reduction η",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 95,
        min: 40,
        max: 99,
        step: 1,
        hint: "Set 100 if the catalog gearbox is the only reduction.",
      },
      {
        key: "dutyCycle",
        label: "Duty cycle",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 40,
        min: 5,
        max: 100,
        step: 5,
        hint: "Index time over station time.",
      },
      {
        key: "safetyFactor",
        label: "Safety factor",
        unit: "—",
        metricToSi: 1,
        defaultValue: 1.4,
        min: 1,
        max: 3,
        step: 0.05,
        hint: "Covers payload variation.",
      },
    ],
    selects: [
      {
        key: "dutyType",
        label: "IEC duty",
        defaultValue: "S5",
        hint: "Indexers are S3 or S5.",
        options: [
          { value: "S1", label: "S1 — continuous" },
          { value: "S3", label: "S3 — intermittent" },
          { value: "S5", label: "S5 — intermittent + braking" },
        ],
      },
    ],
  },
  {
    id: "mixer",
    name: "Mixer / agitator",
    short: "Mixer",
    group: "process",
    description:
      "Impeller power from the Newtonian power number. Torque follows from shaft speed once power is known.",
    fields: [
      {
        key: "density",
        label: "Fluid density",
        unit: "kg/m³",
        metricToSi: 1,
        defaultValue: 1000,
        min: 50,
        max: 3000,
        step: 10,
        hint: "Water is 1000 kg/m³. Slurries run higher.",
      },
      {
        key: "impellerDiaM",
        label: "Impeller diameter",
        unit: "mm",
        metricToSi: 0.001,
        defaultValue: 450,
        min: 50,
        max: 3000,
        step: 5,
        hint: "D of the primary impeller.",
      },
      {
        key: "speedRpm",
        label: "Shaft speed",
        unit: "rpm",
        metricToSi: 1,
        defaultValue: 90,
        min: 5,
        max: 1500,
        step: 5,
        hint: "Impeller rotational speed.",
      },
      {
        key: "powerNumber",
        label: "Power number Np",
        unit: "—",
        metricToSi: 1,
        defaultValue: 5.5,
        min: 0.2,
        max: 12,
        step: 0.1,
        hint: "Rushton ~5–6, hydrofoil ~0.3–0.8, anchor high viscosity ~3–8.",
      },
      {
        key: "serviceFactor",
        label: "Process factor",
        unit: "—",
        metricToSi: 1,
        defaultValue: 1.2,
        min: 1,
        max: 2.5,
        step: 0.05,
        hint: "Start-up in a settled tank, non-Newtonian fluids.",
      },
      {
        key: "efficiency",
        label: "Drive efficiency",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 92,
        min: 50,
        max: 99,
        step: 1,
        hint: "Seal and existing reduction.",
      },
      {
        key: "dutyCycle",
        label: "Duty cycle",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 100,
        min: 5,
        max: 100,
        step: 5,
        hint: "Batch mixers may sit below 100%.",
      },
      {
        key: "safetyFactor",
        label: "Safety factor",
        unit: "—",
        metricToSi: 1,
        defaultValue: 1.25,
        min: 1,
        max: 3,
        step: 0.05,
        hint: "On top of the process factor.",
      },
    ],
    selects: [
      {
        key: "dutyType",
        label: "IEC duty",
        defaultValue: "S1",
        hint: "Most agitators run S1.",
        options: [
          { value: "S1", label: "S1 — continuous" },
          { value: "S3", label: "S3 — intermittent" },
          { value: "S5", label: "S5 — intermittent + braking" },
        ],
      },
    ],
  },
  {
    id: "fan",
    name: "Fan / blower",
    short: "Fan",
    group: "process",
    description:
      "Shaft power from volume flow and total pressure. Torque is power over rotational speed.",
    fields: [
      {
        key: "flowM3s",
        label: "Volume flow",
        unit: "m³/h",
        metricToSi: 1 / 3600,
        defaultValue: 8000,
        min: 50,
        max: 200000,
        step: 50,
        hint: "Inlet volume flow.",
      },
      {
        key: "pressurePa",
        label: "Total pressure",
        unit: "Pa",
        metricToSi: 1,
        defaultValue: 1200,
        min: 20,
        max: 20000,
        step: 10,
        hint: "Fan static + dynamic pressure.",
      },
      {
        key: "speedRpm",
        label: "Fan speed",
        unit: "rpm",
        metricToSi: 1,
        defaultValue: 1450,
        min: 200,
        max: 3600,
        step: 10,
        hint: "Impeller speed, not motor nameplate.",
      },
      {
        key: "efficiency",
        label: "Fan total efficiency",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 68,
        min: 30,
        max: 90,
        step: 1,
        hint: "Aerodynamic efficiency of the impeller.",
      },
      {
        key: "dutyCycle",
        label: "Duty cycle",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 100,
        min: 5,
        max: 100,
        step: 5,
        hint: "HVAC fans are typically S1.",
      },
      {
        key: "safetyFactor",
        label: "Safety factor",
        unit: "—",
        metricToSi: 1,
        defaultValue: 1.15,
        min: 1,
        max: 2,
        step: 0.05,
        hint: "Covers filter loading and density variation.",
      },
    ],
    selects: [
      {
        key: "dutyType",
        label: "IEC duty",
        defaultValue: "S1",
        hint: "Continuous ventilation.",
        options: [
          { value: "S1", label: "S1 — continuous" },
          { value: "S3", label: "S3 — intermittent" },
          { value: "S5", label: "S5 — intermittent + braking" },
        ],
      },
    ],
  },
  {
    id: "pump",
    name: "Centrifugal pump",
    short: "Pump",
    group: "process",
    description:
      "Hydraulic power from flow, head and density. Shaft torque is hydraulic power over efficiency and speed.",
    fields: [
      {
        key: "flowM3s",
        label: "Flow",
        unit: "m³/h",
        metricToSi: 1 / 3600,
        defaultValue: 40,
        min: 0.2,
        max: 2000,
        step: 1,
        hint: "Duty-point capacity.",
      },
      {
        key: "headM",
        label: "Total head",
        unit: "m",
        metricToSi: 1,
        defaultValue: 28,
        min: 0.5,
        max: 300,
        step: 0.5,
        hint: "Differential head at the duty point.",
      },
      {
        key: "density",
        label: "Fluid density",
        unit: "kg/m³",
        metricToSi: 1,
        defaultValue: 1000,
        min: 400,
        max: 2000,
        step: 10,
        hint: "Water = 1000. Imperial field is specific gravity.",
      },
      {
        key: "speedRpm",
        label: "Pump speed",
        unit: "rpm",
        metricToSi: 1,
        defaultValue: 1450,
        min: 200,
        max: 3600,
        step: 10,
        hint: "Impeller speed.",
      },
      {
        key: "efficiency",
        label: "Pump efficiency",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 72,
        min: 30,
        max: 92,
        step: 1,
        hint: "Hydraulic efficiency at the duty point.",
      },
      {
        key: "dutyCycle",
        label: "Duty cycle",
        unit: "%",
        metricToSi: 0.01,
        defaultValue: 100,
        min: 5,
        max: 100,
        step: 5,
        hint: "Process pumps are usually S1.",
      },
      {
        key: "safetyFactor",
        label: "Safety factor",
        unit: "—",
        metricToSi: 1,
        defaultValue: 1.15,
        min: 1,
        max: 2,
        step: 0.05,
        hint: "ISO / HI often apply 1.1–1.15 on absorbed power.",
      },
    ],
    selects: [
      {
        key: "dutyType",
        label: "IEC duty",
        defaultValue: "S1",
        hint: "Continuous pumping.",
        options: [
          { value: "S1", label: "S1 — continuous" },
          { value: "S3", label: "S3 — intermittent" },
          { value: "S5", label: "S5 — intermittent + braking" },
        ],
      },
    ],
  },
];

export function getApplication(id: ApplicationId): ApplicationDef {
  const found = APPLICATIONS.find((a) => a.id === id);
  if (!found) throw new Error(`Unknown application ${id}`);
  return found;
}

export function defaultInputs(id: ApplicationId): Record<string, number | string> {
  const app = getApplication(id);
  const out: Record<string, number | string> = {};
  for (const f of app.fields) out[f.key] = f.defaultValue;
  for (const s of app.selects) out[s.key] = s.defaultValue;
  return out;
}
