import type { ApplicationDef, ApplicationId, FieldDef, SelectFieldDef } from "./types";

function num(
  key: string,
  label: string,
  unit: string,
  def: number,
  extra: Partial<FieldDef> = {},
): FieldDef {
  return {
    key,
    label,
    unit,
    metricToSi: extra.metricToSi ?? 1,
    defaultValue: def,
    min: extra.min ?? 0,
    max: extra.max ?? 1e6,
    step: extra.step ?? 1,
    hint: extra.hint ?? "",
    diagram: extra.diagram,
    visibleWhen: extra.visibleWhen,
  };
}

const DUTY: SelectFieldDef = {
  key: "dutyType",
  label: "IEC duty",
  defaultValue: "S5",
  hint: "S1 continuous, S3 intermittent, S5 intermittent with braking.",
  options: [
    { value: "S1", label: "S1 — continuous" },
    { value: "S3", label: "S3 — intermittent" },
    { value: "S5", label: "S5 — intermittent + braking" },
  ],
};

export const APPLICATIONS: ApplicationDef[] = [
  {
    id: "conveyor",
    name: "Belt conveyor",
    short: "Belt",
    group: "linear",
    description: "Belt pull from payload, incline, friction and acceleration. Torque at the drive pulley.",
    fields: [
      num("payloadKg", "Payload on belt", "kg", 800, { min: 1, max: 50000, step: 10, hint: "Enter kilograms of product on the carrying side.", diagram: "mass" }),
      num("beltMassKg", "Belt + idler mass", "kg", 220, { max: 20000, step: 5, hint: "Enter kilograms. Equivalent translating mass of belt and idlers.", diagram: "mass" }),
      num("speedMps", "Belt speed", "m/s", 0.6, { min: 0.01, max: 8, step: 0.05, hint: "Enter metres per second, e.g. 0.6. Not mm/s.", diagram: "speed" }),
      num("pulleyDiaM", "Drive pulley diameter", "mm", 220, { min: 40, max: 2000, step: 5, metricToSi: 0.001, hint: "Enter millimetres of pitch diameter. 220 means 220 mm.", diagram: "pulley" }),
      num("inclineDeg", "Incline", "deg", 8, { max: 30, step: 0.5, hint: "Enter degrees above horizontal. 0 is flat, 8 is a typical incline.", diagram: "incline" }),
      num("mu", "Equivalent friction μ", "—", 0.12, { min: 0.02, max: 0.6, step: 0.01, hint: "0.08–0.15 typical for roller beds." }),
      num("accelTimeS", "Acceleration time", "s", 1.5, { min: 0.1, max: 30, step: 0.1, hint: "Time to belt speed." }),
      num("efficiency", "Drive efficiency", "%", 92, { min: 40, max: 99, metricToSi: 0.01, hint: "Pulley wrap and couplings." }),
      num("dutyCycle", "Duty cycle", "%", 80, { min: 5, max: 100, step: 5, metricToSi: 0.01, hint: "Running fraction of the cycle." }),
      num("safetyFactor", "Safety factor", "—", 1.4, { min: 1, max: 3, step: 0.05, hint: "Covers start-up and unmodelled drag." }),
    ],
    selects: [{ ...DUTY, defaultValue: "S1" }],
  },
  {
    id: "roller-conveyor",
    name: "Driven roller conveyor",
    short: "Rollers",
    group: "linear",
    description: "Zone drive from rolling resistance and acceleration of product plus rollers.",
    fields: [
      num("payloadKg", "Product mass", "kg", 450, { min: 1, max: 20000, step: 5, hint: "Enter kilograms of product on the driven zone.", diagram: "mass" }),
      num("rollerMassKg", "Driven roller mass", "kg", 80, { max: 5000, hint: "Enter kilograms. Sum of rotating roller masses.", diagram: "mass" }),
      num("speedMps", "Transport speed", "m/s", 0.45, { min: 0.01, max: 4, step: 0.05, hint: "Enter metres per second of package speed.", diagram: "speed" }),
      num("rollerDiaM", "Roller diameter", "mm", 50, { min: 20, max: 200, metricToSi: 0.001, hint: "Enter millimetres of outer diameter, e.g. 50.", diagram: "roller" }),
      num("mu", "Rolling resistance c", "—", 0.03, { min: 0.005, max: 0.2, step: 0.005, hint: "0.02–0.04 for clean steel rollers." }),
      num("accelTimeS", "Acceleration time", "s", 0.6, { min: 0.1, max: 10, step: 0.1, hint: "Zone start time." }),
      num("efficiency", "Drive efficiency", "%", 88, { min: 40, max: 99, metricToSi: 0.01, hint: "Poly-V, line-shaft or MDR." }),
      num("dutyCycle", "Duty cycle", "%", 55, { min: 5, max: 100, step: 5, metricToSi: 0.01, hint: "Accumulation often sits below 100%." }),
      num("safetyFactor", "Safety factor", "—", 1.5, { min: 1, max: 3, step: 0.05, hint: "Dirty rollers and misalignment." }),
    ],
    selects: [{ ...DUTY, defaultValue: "S3" }],
  },
  {
    id: "crane",
    name: "Crane / hoist",
    short: "Hoist",
    group: "lifting",
    description: "Drum torque with reeving. Includes raise, lower and holding torque.",
    fields: [
      num("payloadKg", "Hook load", "kg", 2000, { min: 10, max: 100000, step: 10, hint: "Enter kilograms at the hook.", diagram: "mass" }),
      num("hookSpeedMps", "Hook speed", "m/min", 8, { min: 0.2, max: 60, step: 0.5, metricToSi: 1 / 60, hint: "Enter metres per minute, e.g. 8. Not m/s.", diagram: "hoist" }),
      num("drumDiaM", "Drum diameter", "mm", 320, { min: 50, max: 2000, step: 5, metricToSi: 0.001, hint: "Enter millimetres of pitch diameter.", diagram: "drum" }),
      num("falls", "Number of falls", "—", 4, { min: 1, max: 16, hint: "Count of rope parts supporting the load. Integer.", diagram: "falls" }),
      num("accelTimeS", "Acceleration time", "s", 1.2, { min: 0.2, max: 10, step: 0.1, hint: "Time to rated hook speed." }),
      num("efficiency", "Reeving + gearbox η", "%", 88, { min: 40, max: 98, metricToSi: 0.01, hint: "Sheaves, drum and existing reduction." }),
      num("dutyCycle", "Duty cycle", "%", 40, { min: 5, max: 100, step: 5, metricToSi: 0.01, hint: "FEM / ISO hoist running fraction." }),
      num("safetyFactor", "Safety factor", "—", 1.6, { min: 1.1, max: 3, step: 0.05, hint: "Lifting uses a higher factor." }),
    ],
    selects: [{ ...DUTY, defaultValue: "S3" }],
  },
  {
    id: "winch",
    name: "Winch / capstan",
    short: "Winch",
    group: "lifting",
    description: "Single-fall drum. Raise, lower and holding torque on the line.",
    fields: [
      num("payloadKg", "Line-pull mass equivalent", "kg", 600, { min: 5, max: 50000, step: 5, hint: "Enter kilograms. If you know line pull in newtons, use F / 9.81.", diagram: "mass" }),
      num("lineSpeedMps", "Line speed", "m/min", 12, { min: 0.2, max: 80, step: 0.5, metricToSi: 1 / 60, hint: "Enter metres per minute of cable speed.", diagram: "hoist" }),
      num("drumDiaM", "Drum diameter", "mm", 280, { min: 40, max: 2000, step: 5, metricToSi: 0.001, hint: "Enter millimetres of mean winding diameter.", diagram: "drum" }),
      num("accelTimeS", "Acceleration time", "s", 1, { min: 0.2, max: 15, step: 0.1, hint: "Time to line speed." }),
      num("efficiency", "Drive efficiency", "%", 90, { min: 40, max: 98, metricToSi: 0.01, hint: "Drum bearings plus existing reduction." }),
      num("dutyCycle", "Duty cycle", "%", 35, { min: 5, max: 100, step: 5, metricToSi: 0.01, hint: "Winches are rarely continuous." }),
      num("safetyFactor", "Safety factor", "—", 1.7, { min: 1.1, max: 3, step: 0.05, hint: "Includes snatch loads." }),
    ],
    selects: [{ ...DUTY, defaultValue: "S3" }],
  },
  {
    id: "ball-screw",
    name: "Ball screw / linear actuator",
    short: "Screw",
    group: "linear",
    description:
      "Rotary to axial through screw lead. Horizontal, inclined or vertical lift — raise, lower and hold.",
    fields: [
      num("payloadKg", "Moved mass", "kg", 180, { min: 0.5, max: 10000, hint: "Enter kilograms of carriage, tooling and workpiece.", diagram: "mass" }),
      num("speedMps", "Linear speed", "mm/s", 250, { min: 1, max: 2000, step: 5, metricToSi: 0.001, hint: "Enter millimetres per second, e.g. 250. Not m/s.", diagram: "speed" }),
      num("leadM", "Screw lead", "mm/rev", 10, { min: 1, max: 50, metricToSi: 0.001, hint: "Enter millimetres of travel per revolution, e.g. 10.", diagram: "lead" }),
      num("inclineDeg", "Axis incline", "deg", 15, {
        max: 90,
        hint: "Enter degrees from horizontal. Used only when orientation is Inclined.",
        diagram: "incline",
        visibleWhen: { key: "orientation", values: ["inclined"] },
      }),
      num("counterweightKg", "Counterweight", "kg", 0, {
        max: 20000,
        hint: "Enter kilograms of balance mass. 0 if none.",
        diagram: "counterweight",
        visibleWhen: { key: "orientation", values: ["inclined", "vertical"] },
      }),
      num("mu", "Guide friction μ", "—", 0.01, { max: 0.3, step: 0.005, hint: "Profile rail ~0.005–0.02." }),
      num("preloadN", "Seal / preload force", "N", 40, { max: 5000, step: 5, hint: "Wiper drag plus preload." }),
      num("accelTimeS", "Acceleration time", "s", 0.25, { min: 0.05, max: 5, step: 0.05, hint: "Time to linear speed." }),
      num("efficiency", "Screw efficiency", "%", 90, { min: 30, max: 98, metricToSi: 0.01, hint: "Ball screw ~90%, acme 30–50%." }),
      num("dutyCycle", "Duty cycle", "%", 50, { min: 5, max: 100, step: 5, metricToSi: 0.01, hint: "Move time over cycle time." }),
      num("safetyFactor", "Safety factor", "—", 1.35, { min: 1, max: 3, step: 0.05, hint: "Servo axes often 1.3–1.5." }),
    ],
    selects: [
      {
        key: "orientation",
        label: "Axis orientation",
        defaultValue: "horizontal",
        hint: "Vertical includes gravity on raise, lower and holding.",
        options: [
          { value: "horizontal", label: "Horizontal" },
          { value: "inclined", label: "Inclined" },
          { value: "vertical", label: "Vertical lift" },
        ],
      },
      DUTY,
    ],
  },
  {
    id: "rack-pinion",
    name: "Rack and pinion",
    short: "Rack",
    group: "linear",
    description: "Long-travel axis. Set orientation to vertical for a rack lift, including lowering.",
    fields: [
      num("payloadKg", "Moved mass", "kg", 350, { min: 1, max: 20000, step: 5, hint: "Enter kilograms of carriage plus payload.", diagram: "mass" }),
      num("speedMps", "Linear speed", "m/s", 1.2, { min: 0.05, max: 6, step: 0.05, hint: "Enter metres per second of rapid traverse.", diagram: "speed" }),
      num("pinionDiaM", "Pinion pitch diameter", "mm", 80, { min: 20, max: 400, metricToSi: 0.001, hint: "Enter millimetres of pitch-circle diameter.", diagram: "pinion" }),
      num("inclineDeg", "Axis incline", "deg", 10, {
        max: 90,
        hint: "Enter degrees from horizontal.",
        diagram: "incline",
        visibleWhen: { key: "orientation", values: ["inclined"] },
      }),
      num("counterweightKg", "Counterweight", "kg", 0, {
        max: 20000,
        hint: "Enter kilograms of optional balance mass.",
        diagram: "counterweight",
        visibleWhen: { key: "orientation", values: ["inclined", "vertical"] },
      }),
      num("mu", "Guide friction μ", "—", 0.015, { max: 0.3, step: 0.005, hint: "Linear guide friction." }),
      num("accelTimeS", "Acceleration time", "s", 0.4, { min: 0.05, max: 8, step: 0.05, hint: "Time to traverse speed." }),
      num("efficiency", "Mesh efficiency", "%", 95, { min: 70, max: 99, metricToSi: 0.01, hint: "Straight or helical rack." }),
      num("dutyCycle", "Duty cycle", "%", 45, { min: 5, max: 100, step: 5, metricToSi: 0.01, hint: "Move time over cycle time." }),
      num("safetyFactor", "Safety factor", "—", 1.4, { min: 1, max: 3, step: 0.05, hint: "Contamination and mesh wear." }),
    ],
    selects: [
      {
        key: "orientation",
        label: "Axis orientation",
        defaultValue: "horizontal",
        hint: "Vertical is a rack-driven Z lift.",
        options: [
          { value: "horizontal", label: "Horizontal" },
          { value: "inclined", label: "Inclined" },
          { value: "vertical", label: "Vertical lift" },
        ],
      },
      DUTY,
    ],
  },
  {
    id: "gantry",
    name: "Gantry / cartesian axis",
    short: "Gantry",
    group: "linear",
    description: "Belt-driven module. Switch to vertical for a Z-axis lift with raise and lower.",
    fields: [
      num("payloadKg", "Moved mass", "kg", 55, { min: 0.2, max: 2000, hint: "Enter kilograms of carriage, end-effector and part.", diagram: "mass" }),
      num("speedMps", "Linear speed", "m/s", 2, { min: 0.05, max: 10, step: 0.05, hint: "Enter metres per second of peak traverse.", diagram: "speed" }),
      num("pulleyDiaM", "Drive pulley diameter", "mm", 48, { min: 16, max: 200, metricToSi: 0.001, hint: "Enter millimetres of timing-pulley pitch diameter.", diagram: "pulley" }),
      num("counterweightKg", "Counterweight", "kg", 0, {
        max: 2000,
        hint: "Enter kilograms. Used on a vertical Z axis.",
        diagram: "counterweight",
        visibleWhen: { key: "orientation", values: ["vertical"] },
      }),
      num("mu", "Guide friction μ", "—", 0.012, { max: 0.2, step: 0.002, hint: "Rail plus belt tooth friction." }),
      num("accelTimeS", "Acceleration time", "s", 0.2, { min: 0.05, max: 4, step: 0.05, hint: "Pick-and-place ramps 0.1–0.3 s." }),
      num("efficiency", "Belt efficiency", "%", 95, { min: 70, max: 99, metricToSi: 0.01, hint: "Timing belt typically 94–97%." }),
      num("dutyCycle", "Duty cycle", "%", 60, { min: 5, max: 100, step: 5, metricToSi: 0.01, hint: "High-cycle machines approach 70%." }),
      num("safetyFactor", "Safety factor", "—", 1.3, { min: 1, max: 3, step: 0.05, hint: "Servo sizing commonly 1.25–1.4." }),
    ],
    selects: [
      {
        key: "orientation",
        label: "Axis orientation",
        defaultValue: "horizontal",
        hint: "Vertical is a belt-driven Z lift.",
        options: [
          { value: "horizontal", label: "Horizontal" },
          { value: "vertical", label: "Vertical lift" },
        ],
      },
      DUTY,
    ],
  },
  {
    id: "vertical-lift",
    name: "Vertical linear lift",
    short: "Lift",
    group: "lifting",
    description: "Dedicated Z-axis. Ball screw, belt or rack — raise, lower, stop and holding torque.",
    fields: [
      num("payloadKg", "Lifted mass", "kg", 250, { min: 1, max: 20000, hint: "Enter kilograms of carriage, fixture and payload.", diagram: "mass" }),
      num("counterweightKg", "Counterweight", "kg", 0, { max: 20000, hint: "Enter kilograms of balance mass. 0 if uncompensated.", diagram: "counterweight" }),
      num("speedMps", "Lift speed", "mm/s", 200, { min: 1, max: 2000, step: 5, metricToSi: 0.001, hint: "Enter millimetres per second of raise / lower speed.", diagram: "speed" }),
      num("leadM", "Screw lead", "mm/rev", 10, {
        min: 1,
        max: 50,
        metricToSi: 0.001,
        hint: "Enter millimetres of travel per revolution.",
        diagram: "lead",
        visibleWhen: { key: "mechanism", values: ["ball-screw"] },
      }),
      num("pulleyDiaM", "Drive pulley diameter", "mm", 48, {
        min: 16,
        max: 400,
        metricToSi: 0.001,
        hint: "Enter millimetres of timing-pulley pitch diameter.",
        diagram: "pulley",
        visibleWhen: { key: "mechanism", values: ["belt"] },
      }),
      num("pinionDiaM", "Pinion pitch diameter", "mm", 80, {
        min: 20,
        max: 400,
        metricToSi: 0.001,
        hint: "Enter millimetres of rack pinion pitch circle.",
        diagram: "pinion",
        visibleWhen: { key: "mechanism", values: ["rack"] },
      }),
      num("mu", "Guide friction μ", "—", 0.01, { max: 0.2, step: 0.005, hint: "Vertical gravity is separate from guide drag." }),
      num("preloadN", "Seal / wiper drag", "N", 40, { max: 5000, step: 5, hint: "Constant drag, independent of gravity." }),
      num("accelTimeS", "Acceleration time", "s", 0.3, { min: 0.05, max: 8, step: 0.05, hint: "Time to lift speed." }),
      num("efficiency", "Mechanism efficiency", "%", 90, { min: 30, max: 98, metricToSi: 0.01, hint: "Ball screw ~90%, belt/rack ~95%." }),
      num("dutyCycle", "Duty cycle", "%", 40, { min: 5, max: 100, step: 5, metricToSi: 0.01, hint: "Move time over cycle time." }),
      num("safetyFactor", "Safety factor", "—", 1.5, { min: 1.1, max: 3, step: 0.05, hint: "Lifts use a higher factor." }),
    ],
    selects: [
      {
        key: "mechanism",
        label: "Lift mechanism",
        defaultValue: "ball-screw",
        hint: "Changes how axial force becomes shaft torque.",
        options: [
          { value: "ball-screw", label: "Ball screw" },
          { value: "belt", label: "Toothed belt" },
          { value: "rack", label: "Rack and pinion" },
        ],
      },
      DUTY,
    ],
  },
  {
    id: "rotary-table",
    name: "Rotary table / indexer",
    short: "Rotary",
    group: "rotary",
    description: "Torque from table inertia, angular acceleration, friction and unbalance.",
    fields: [
      num("tableInertia", "Table + fixture inertia", "kg·m²", 12, { min: 0.01, max: 5000, step: 0.1, hint: "Enter kg·m² about the rotation axis. Disk ≈ ½ m r².", diagram: "inertia" }),
      num("payloadInertia", "Payload inertia", "kg·m²", 4, { max: 5000, step: 0.1, hint: "Enter kg·m² of parts on the table, same axis.", diagram: "inertia" }),
      num("speedRpm", "Table speed", "rpm", 30, { min: 0.2, max: 600, hint: "Enter revolutions per minute.", diagram: "rpm" }),
      num("fricTorqueNm", "Friction torque", "N·m", 8, { max: 2000, step: 0.5, hint: "Enter newton-metres of seal and bearing drag.", diagram: "torque" }),
      num("unbalanceNm", "Unbalance / gravity torque", "N·m", 0, { max: 5000, hint: "Enter N·m. Offset payload ≈ m · g · e.", diagram: "torque" }),
      num("accelTimeS", "Acceleration time", "s", 0.8, { min: 0.05, max: 20, step: 0.05, hint: "Time to table speed." }),
      num("efficiency", "Existing reduction η", "%", 95, { min: 40, max: 99, metricToSi: 0.01, hint: "100 if the catalog gearbox is the only reduction." }),
      num("dutyCycle", "Duty cycle", "%", 40, { min: 5, max: 100, step: 5, metricToSi: 0.01, hint: "Index time over station time." }),
      num("safetyFactor", "Safety factor", "—", 1.4, { min: 1, max: 3, step: 0.05, hint: "Payload variation." }),
    ],
    selects: [DUTY],
  },
  {
    id: "mixer",
    name: "Mixer / agitator",
    short: "Mixer",
    group: "process",
    description: "Impeller power from the Newtonian power number. Torque from shaft speed.",
    fields: [
      num("density", "Fluid density", "kg/m³", 1000, { min: 50, max: 3000, step: 10, hint: "Enter kilograms per cubic metre. Water is 1000.", diagram: "density" }),
      num("impellerDiaM", "Impeller diameter", "mm", 450, { min: 50, max: 3000, step: 5, metricToSi: 0.001, hint: "Enter millimetres of primary impeller diameter.", diagram: "impeller" }),
      num("speedRpm", "Shaft speed", "rpm", 90, { min: 5, max: 1500, step: 5, hint: "Enter revolutions per minute of the impeller.", diagram: "rpm" }),
      num("powerNumber", "Power number Np", "—", 5.5, { min: 0.2, max: 12, step: 0.1, hint: "Rushton ~5–6, hydrofoil ~0.3–0.8." }),
      num("serviceFactor", "Process factor", "—", 1.2, { min: 1, max: 2.5, step: 0.05, hint: "Start-up in a settled tank." }),
      num("efficiency", "Drive efficiency", "%", 92, { min: 50, max: 99, metricToSi: 0.01, hint: "Seal and existing reduction." }),
      num("dutyCycle", "Duty cycle", "%", 100, { min: 5, max: 100, step: 5, metricToSi: 0.01, hint: "Batch mixers may sit below 100%." }),
      num("safetyFactor", "Safety factor", "—", 1.25, { min: 1, max: 3, step: 0.05, hint: "On top of the process factor." }),
    ],
    selects: [{ ...DUTY, defaultValue: "S1" }],
  },
  {
    id: "fan",
    name: "Fan / blower",
    short: "Fan",
    group: "process",
    description: "Shaft power from volume flow and total pressure.",
    fields: [
      num("flowM3s", "Volume flow", "m³/h", 8000, { min: 50, max: 200000, step: 50, metricToSi: 1 / 3600, hint: "Enter cubic metres per hour, not m³/s.", diagram: "flow" }),
      num("pressurePa", "Total pressure", "Pa", 1200, { min: 20, max: 20000, step: 10, hint: "Enter pascals (N/m²). 1200 Pa = 1.2 kPa.", diagram: "pressure" }),
      num("speedRpm", "Fan speed", "rpm", 1450, { min: 200, max: 3600, step: 10, hint: "Enter revolutions per minute.", diagram: "rpm" }),
      num("efficiency", "Fan total efficiency", "%", 68, { min: 30, max: 90, metricToSi: 0.01, hint: "Aerodynamic efficiency." }),
      num("dutyCycle", "Duty cycle", "%", 100, { min: 5, max: 100, step: 5, metricToSi: 0.01, hint: "HVAC fans are typically S1." }),
      num("safetyFactor", "Safety factor", "—", 1.15, { min: 1, max: 2, step: 0.05, hint: "Filter loading and density variation." }),
    ],
    selects: [{ ...DUTY, defaultValue: "S1" }],
  },
  {
    id: "pump",
    name: "Centrifugal pump",
    short: "Pump",
    group: "process",
    description: "Hydraulic power from flow, head and density.",
    fields: [
      num("flowM3s", "Flow", "m³/h", 40, { min: 0.2, max: 2000, metricToSi: 1 / 3600, hint: "Enter cubic metres per hour at the duty point.", diagram: "flow" }),
      num("headM", "Total head", "m", 28, { min: 0.5, max: 300, step: 0.5, hint: "Enter metres of liquid column.", diagram: "head" }),
      num("density", "Fluid density", "kg/m³", 1000, { min: 400, max: 2000, step: 10, hint: "Enter kg/m³. Water = 1000.", diagram: "density" }),
      num("speedRpm", "Pump speed", "rpm", 1450, { min: 200, max: 3600, step: 10, hint: "Enter revolutions per minute.", diagram: "rpm" }),
      num("efficiency", "Pump efficiency", "%", 72, { min: 30, max: 92, metricToSi: 0.01, hint: "Hydraulic efficiency at the duty point." }),
      num("dutyCycle", "Duty cycle", "%", 100, { min: 5, max: 100, step: 5, metricToSi: 0.01, hint: "Process pumps are usually S1." }),
      num("safetyFactor", "Safety factor", "—", 1.15, { min: 1, max: 2, step: 0.05, hint: "Often 1.1–1.15 on absorbed power." }),
    ],
    selects: [{ ...DUTY, defaultValue: "S1" }],
  },
];

export function getApplication(id: ApplicationId): ApplicationDef {
  const found = APPLICATIONS.find((a) => a.id === id);
  if (!found) throw new Error(`Unknown application ${id}`);
  return found;
}

export function defaultInputs(id: ApplicationId): Record<string, number | string> {
  const app = getApplication(id);
  const out: Record<string, number | string> = {};
  for (const f of app.fields) out[f.key] = f.defaultValue;
  for (const s of app.selects) out[s.key] = s.defaultValue;
  return out;
}
