/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AxionRouteImport } from './routes/axion'
import { Route as UnitsRouteImport } from './routes/units'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AxionRoute = AxionRouteImport.update({
  id: '/axion',
  path: '/axion',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/axion': typeof AxionRoute
  '/units': typeof UnitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/axion': typeof AxionRoute
  '/units': typeof UnitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/axion': typeof AxionRoute
  '/units': typeof UnitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/axion' | '/units'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/axion' | '/units'
  id: '__root__' | '/' | '/axion' | '/units'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AxionRoute: typeof AxionRoute
  UnitsRoute: typeof UnitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/axion': {
      id: '/axion'
      path: '/axion'
      fullPath: '/axion'
      preLoaderRoute: typeof AxionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AxionRoute: AxionRoute,
  UnitsRoute: UnitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
