/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AxionRouteImport } from './routes/axion'
import { Route as CaliperRouteImport } from './routes/caliper'
import { Route as GraniaRouteImport } from './routes/grania'
import { Route as LibrarianRouteImport } from './routes/librarian'
import { Route as LobeRouteImport } from './routes/lobe'
import { Route as UnitsRouteImport } from './routes/units'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AxionRoute = AxionRouteImport.update({
  id: '/axion',
  path: '/axion',
  getParentRoute: () => rootRouteImport,
} as any)
const CaliperRoute = CaliperRouteImport.update({
  id: '/caliper',
  path: '/caliper',
  getParentRoute: () => rootRouteImport,
} as any)
const GraniaRoute = GraniaRouteImport.update({
  id: '/grania',
  path: '/grania',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarianRoute = LibrarianRouteImport.update({
  id: '/librarian',
  path: '/librarian',
  getParentRoute: () => rootRouteImport,
} as any)
const LobeRoute = LobeRouteImport.update({
  id: '/lobe',
  path: '/lobe',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/axion': typeof AxionRoute
  '/caliper': typeof CaliperRoute
  '/grania': typeof GraniaRoute
  '/librarian': typeof LibrarianRoute
  '/lobe': typeof LobeRoute
  '/units': typeof UnitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/axion': typeof AxionRoute
  '/caliper': typeof CaliperRoute
  '/grania': typeof GraniaRoute
  '/librarian': typeof LibrarianRoute
  '/lobe': typeof LobeRoute
  '/units': typeof UnitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/axion': typeof AxionRoute
  '/caliper': typeof CaliperRoute
  '/grania': typeof GraniaRoute
  '/librarian': typeof LibrarianRoute
  '/lobe': typeof LobeRoute
  '/units': typeof UnitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/axion' | '/caliper' | '/grania' | '/librarian' | '/lobe' | '/units'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/axion' | '/caliper' | '/grania' | '/librarian' | '/lobe' | '/units'
  id:
    | '__root__'
    | '/'
    | '/axion'
    | '/caliper'
    | '/grania'
    | '/librarian'
    | '/lobe'
    | '/units'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AxionRoute: typeof AxionRoute
  CaliperRoute: typeof CaliperRoute
  GraniaRoute: typeof GraniaRoute
  LibrarianRoute: typeof LibrarianRoute
  LobeRoute: typeof LobeRoute
  UnitsRoute: typeof UnitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/axion': {
      id: '/axion'
      path: '/axion'
      fullPath: '/axion'
      preLoaderRoute: typeof AxionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caliper': {
      id: '/caliper'
      path: '/caliper'
      fullPath: '/caliper'
      preLoaderRoute: typeof CaliperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grania': {
      id: '/grania'
      path: '/grania'
      fullPath: '/grania'
      preLoaderRoute: typeof GraniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/librarian': {
      id: '/librarian'
      path: '/librarian'
      fullPath: '/librarian'
      preLoaderRoute: typeof LibrarianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobe': {
      id: '/lobe'
      path: '/lobe'
      fullPath: '/lobe'
      preLoaderRoute: typeof LobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AxionRoute: AxionRoute,
  CaliperRoute: CaliperRoute,
  GraniaRoute: GraniaRoute,
  LibrarianRoute: LibrarianRoute,
  LobeRoute: LobeRoute,
  UnitsRoute: UnitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
